# -*- coding: utf-8 -*-
"""Copy of youtube_shorts_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EvwbVVpY6dXcqG7dRbOnhFaq-uDL9jlu

# 📹 YouTube Shorts Viral Pipeline
Collects metadata and downloads viral YouTube Shorts using the YouTube Data API v3 and `yt-dlp`.

**Pipeline Steps:**
1. Mount Google Drive
2. Install dependencies
3. Configure API & folder structure
4. Search for viral Shorts across multiple queries
5. Filter by minimum view count
6. Collect full metadata per video
7. Download videos with `yt-dlp`
8. Export metadata to CSV

## Cell 1 — Mount Google Drive
"""

from google.colab import drive
drive.mount('/content/drive')
print('✅ Google Drive mounted successfully.')

"""## Cell 2 — Install Dependencies"""

!pip install -q yt-dlp google-api-python-client pandas

"""## Cell 3 — Configuration"""

import os

# ─────────────────────────────────────────────
# 🔑  PASTE YOUR YouTube Data API v3 KEY HERE
# ─────────────────────────────────────────────
YOUTUBE_API_KEY = "AIzaSyCRTtcv9kaDXXDcFp_ocMl8GODiOijMqvo"

# ── Search settings ───────────────────────────
SEARCH_QUERIES = [
    "viral shorts",
    "trending shorts",
    "funny shorts",
    "tutorial shorts",
    "life hack shorts",
    "motivation shorts",
]
MAX_RESULTS_PER_QUERY = 50         # YouTube API max per call = 50
MIN_VIEW_COUNT        = 20_000      # Filter: minimum views
MAX_DURATION_SECONDS  = 50         # Shorts are ≤ 60 seconds

# ── Folder paths ──────────────────────────────
BASE_DIR       = "/content/drive/MyDrive/viral_agent"
VIDEO_DIR      = os.path.join(BASE_DIR, "datasets", "raw_videos", "youtube")
METADATA_DIR   = os.path.join(BASE_DIR, "datasets", "metadata")
CSV_PATH       = os.path.join(METADATA_DIR, "youtube_metadata0.csv")

print(f"Video directory  : {VIDEO_DIR}")
print(f"Metadata CSV     : {CSV_PATH}")

"""## Cell 4 — Create Folder Structure"""

for folder in [VIDEO_DIR, METADATA_DIR]:
    os.makedirs(folder, exist_ok=True)
    print(f"✅ Ready: {folder}")

"""## Cell 5 — Helper Functions"""

import re
import subprocess
from datetime import datetime

from googleapiclient.discovery import build


def build_youtube_client(api_key: str):
    """Build and return a YouTube Data API v3 client."""
    return build("youtube", "v3", developerKey=api_key)


def parse_iso8601_duration(duration_str: str) -> int:
    """
    Convert ISO 8601 duration (e.g. 'PT1M3S') to total seconds.
    Returns 0 if parsing fails.
    """
    try:
        match = re.match(
            r'PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?',
            duration_str
        )
        if not match:
            return 0
        hours   = int(match.group(1) or 0)
        minutes = int(match.group(2) or 0)
        seconds = int(match.group(3) or 0)
        return hours * 3600 + minutes * 60 + seconds
    except Exception:
        return 0


def search_shorts(youtube, query: str, max_results: int = 20) -> list[str]:
    """
    Search YouTube for Shorts matching `query`.
    Returns a list of video IDs.
    """
    try:
        response = youtube.search().list(
            q=query + " #shorts",   # boost Shorts discovery
            part="id",
            type="video",
            videoDuration="short",  # ≤ 4 min filter from API side
            order="viewCount",
            maxResults=max_results,
            relevanceLanguage="en",
        ).execute()
        return [item["id"]["videoId"] for item in response.get("items", [])]
    except Exception as e:
        print(f"  ⚠️  Search error for '{query}': {e}")
        return []


def get_video_details(youtube, video_ids: list[str]) -> list[dict]:
    """
    Fetch snippet, contentDetails, and statistics for up to 50 video IDs.
    Returns a list of raw video resource dicts.
    """
    try:
        response = youtube.videos().list(
            id=",".join(video_ids),
            part="snippet,contentDetails,statistics",
        ).execute()
        return response.get("items", [])
    except Exception as e:
        print(f"  ⚠️  Details fetch error: {e}")
        return []


def build_metadata_record(
    video: dict,
    source_query: str,
    local_video_path: str = "",
) -> dict:
    """
    Build a flat metadata dict from a YouTube video resource.
    Mirrors the TikTok pipeline field names.
    """
    snippet     = video.get("snippet", {})
    stats       = video.get("statistics", {})
    content     = video.get("contentDetails", {})
    video_id    = video.get("id", "")

    return {
        "platform"         : "youtube",
        "video_id"         : video_id,
        "url"              : f"https://www.youtube.com/shorts/{video_id}",
        "creator_username" : snippet.get("channelTitle", ""),
        "caption_or_title" : snippet.get("title", ""),
        "publish_date"     : snippet.get("publishedAt", ""),
        "views"            : int(stats.get("viewCount", 0)),
        "likes"            : int(stats.get("likeCount", 0)),
        "comments"         : int(stats.get("commentCount", 0)),
        "duration_seconds" : parse_iso8601_duration(content.get("duration", "PT0S")),
        "local_video_path" : local_video_path,
        "source_query"     : source_query,
    }


def download_video(video_id: str, output_dir: str) -> str:
    """
    Download a YouTube Short with yt-dlp.
    Returns the local file path on success, or empty string on failure.
    """
    url      = f"https://www.youtube.com/shorts/{video_id}"
    out_tmpl = os.path.join(output_dir, f"{video_id}.%(ext)s")
    cmd = [
        "yt-dlp",
        "--quiet",
        "--no-warnings",
        "-f", "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best",
        "--merge-output-format", "mp4",
        "-o", out_tmpl,
        url,
    ]
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
        expected_path = os.path.join(output_dir, f"{video_id}.mp4")
        if os.path.exists(expected_path):
            return expected_path
        # Fallback: search for any file matching the video_id
        for fname in os.listdir(output_dir):
            if fname.startswith(video_id):
                return os.path.join(output_dir, fname)
        print(f"    ⚠️  File not found after download for {video_id}")
        return ""
    except subprocess.TimeoutExpired:
        print(f"    ⏱️  Timeout downloading {video_id}")
        return ""
    except Exception as e:
        print(f"    ❌ Download error for {video_id}: {e}")
        return ""


print("✅ Helper functions defined.")

"""## Cell 6 — Collect Metadata for All Queries"""

youtube = build_youtube_client(YOUTUBE_API_KEY)

all_records   = {}   # video_id → metadata dict  (deduplication)
query_id_map  = {}   # video_id → source_query

print(f"🔍 Searching across {len(SEARCH_QUERIES)} queries ...\n")

for query in SEARCH_QUERIES:
    print(f"  Query: '{query}'")
    video_ids = search_shorts(youtube, query, max_results=MAX_RESULTS_PER_QUERY)
    print(f"    Found {len(video_ids)} candidate IDs.")

    if not video_ids:
        continue

    # Batch-fetch full details (API allows up to 50 per call)
    videos = get_video_details(youtube, video_ids)

    passed = 0
    for video in videos:
        video_id = video.get("id", "")
        if not video_id or video_id in all_records:
            continue

        stats    = video.get("statistics", {})
        content  = video.get("contentDetails", {})

        view_count       = int(stats.get("viewCount", 0))
        duration_seconds = parse_iso8601_duration(content.get("duration", "PT0S"))

        # ── Filters ───────────────────────────────────────────
        if view_count < MIN_VIEW_COUNT:
            continue
        if duration_seconds > MAX_DURATION_SECONDS or duration_seconds == 0:
            continue

        record = build_metadata_record(video, source_query=query)
        all_records[video_id] = record
        passed += 1

    print(f"    ✅ {passed} videos passed filters (≥{MIN_VIEW_COUNT:,} views, ≤{MAX_DURATION_SECONDS}s).")

print(f"\n📊 Total unique videos collected: {len(all_records)}")

"""## Cell 7 — Download Videos"""

total_collected  = len(all_records)
total_downloaded = 0

print(f"⬇️  Downloading {total_collected} videos to {VIDEO_DIR}\n")

for i, (video_id, record) in enumerate(all_records.items(), start=1):
    print(f"  [{i}/{total_collected}] {video_id} — {record['caption_or_title'][:60]}")

    local_path = download_video(video_id, VIDEO_DIR)

    if local_path:
        record["local_video_path"] = local_path
        total_downloaded += 1
        print(f"    ✅ Saved: {local_path}")
    else:
        record["local_video_path"] = ""
        print(f"    ❌ Download failed — metadata still recorded.")

print(f"\n✅ Download phase complete: {total_downloaded}/{total_collected} succeeded.")

"""## Cell 8 — Build DataFrame & Export CSV"""

import pandas as pd

COLUMN_ORDER = [
    "platform",
    "video_id",
    "url",
    "creator_username",
    "caption_or_title",
    "publish_date",
    "views",
    "likes",
    "comments",
    "duration_seconds",
    "local_video_path",
    "source_query",
]

df = pd.DataFrame(list(all_records.values()), columns=COLUMN_ORDER)

# Ensure numeric types
for col in ["views", "likes", "comments", "duration_seconds"]:
    df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0).astype(int)

# Sort by views descending
df = df.sort_values("views", ascending=False).reset_index(drop=True)

# Export
df.to_csv(CSV_PATH, index=False, encoding="utf-8-sig")

print("✅ Metadata DataFrame created and exported.")
print()
df.head(5)

"""## Cell 9 — Final Summary"""

print("YOUTUBE SHORTS PIPELINE — SUMMARY")
print(f"  Total videos collected   : {total_collected}")
print(f"  Total videos downloaded  : {total_downloaded}")
print(f"  Failed downloads         : {total_collected - total_downloaded}")
print(f"  DataFrame shape          : {df.shape}")
print(f"  CSV saved to             : {CSV_PATH}")
print("=" * 55)
print()
print("📈 Top 5 videos by views:")
print(
    df[["video_id", "creator_username", "views", "duration_seconds", "source_query"]]
    .head(5)
    .to_string(index=False)
)

